# Generated by Django 3.2.4 on 2021-07-01 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='fecha_nacimiento',
        ),
    ]
