# Generated by Django 3.2.4 on 2021-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0002_remove_especialista_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='telefono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
