# Generated by Django 3.2.4 on 2021-07-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0003_especialista_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorhsc.especialista')),
            ],
        ),
    ]
