# Generated by Django 3.2.4 on 2021-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0005_auto_20210722_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='end',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='start',
            field=models.CharField(max_length=25),
        ),
    ]
