# Generated by Django 3.2.4 on 2021-09-27 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0006_auto_20210722_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetasConsultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevas', models.IntegerField()),
                ('controles', models.IntegerField()),
                ('total', models.IntegerField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorhsc.especialidad')),
            ],
        ),
    ]
