# Generated by Django 3.2.4 on 2021-09-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0007_metasconsultas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetasTotales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalNuevas', models.IntegerField()),
                ('totalControles', models.IntegerField()),
                ('totalTotal', models.IntegerField()),
            ],
        ),
    ]
