# Generated by Django 3.2.4 on 2021-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0009_consultascumplimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultascumplimiento',
            name='name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
