# Generated by Django 3.2.4 on 2021-10-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0010_consultascumplimiento_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadnoGES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tasa_crecimiento', models.FloatField()),
                ('ausentismo', models.FloatField()),
            ],
        ),
    ]
