# Generated by Django 3.2.4 on 2021-11-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0013_nogestotales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidad',
            old_name='ausentismo',
            new_name='rendimiento',
        ),
    ]
