# Generated by Django 3.2.4 on 2021-11-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0014_rename_ausentismo_especialidad_rendimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidad',
            old_name='rendimiento',
            new_name='ausentismo',
        ),
    ]
