# Generated by Django 3.2.4 on 2021-11-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0016_horasnoges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horasnoges',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
