# Generated by Django 3.2.4 on 2021-11-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0018_tothorasnoges'),
    ]

    operations = [
        migrations.AddField(
            model_name='horasnoges',
            name='clave',
            field=models.CharField(default='Perdidas', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tothorasnoges',
            name='clave',
            field=models.CharField(default='Perdidas', max_length=30),
            preserve_default=False,
        ),
    ]
