# Generated by Django 3.2.4 on 2021-11-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorhsc', '0019_auto_20211106_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='rendimiento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
